[infra-tests] Add `self-signed` integration test
This PR adds a new test option called `self-signed` which is used to
enable `self-signed` integration tests. This is done by adding a new
`generate-self-signed` make option, which is called whenever `self_signed`
env variable is enabled.

Once enabled, self-signed certs are genereated and relevant `self-signed-config`
is called to attach those files into `kots` config.

Signed-off-by: Tarun Pothulapati <tarun@gitpod.io>

diff --git a/install/tests/Makefile b/install/tests/Makefile
--- a/install/tests/Makefile
+++ b/install/tests/Makefile
@@ -111,10 +111,14 @@ add-ns-record: check-env-cloud
 .PHONY:
 ## cluster-issuer: Creates a cluster issuer for the correspondign provider
 cluster-issuer: check-env-cloud
+ifndef self_signed
+	@echo "Skipped creating cluster issuer"
+else
 	terraform init --upgrade && \
 	terraform workspace new $(TF_VAR_TEST_ID) || terraform workspace select $(TF_VAR_TEST_ID) && \
 	terraform apply -target=module.$(cloud)-issuer  -var kubeconfig=${KUBECONFIG} --auto-approve
 	@echo "Done creating cluster issuer"
+endif
 
 image_id_1804 := "ubuntu-1804-bionic-v20220712"
 
@@ -252,6 +256,21 @@ registry-config-aws:
 	envsubst < ./manifests/kots-config-aws-registry.yaml > tmp_2_config.yml
 	yq m -i tmp_config.yml tmp_2_config.yml
 
+self-signed-config:
+	# install in local store
+	mkcert -install
+
+	cat "${HOME}"/.local/share/mkcert/rootCA.pem > ./ca.pem
+	mkcert -cert-file "./ssl.crt" \
+	  -key-file "./ssl.key" \
+	  "*.ws.${TF_VAR_TEST_ID}.${DOMAIN}" "*.${TF_VAR_TEST_ID}.${DOMAIN}" "${TF_VAR_TEST_ID}.${DOMAIN}"
+
+	export CA_CERT=$$(cat ./ca.pem | base64 -w 0) && \
+	export SSL_CERT=$$(cat ./ssl.crt | base64 -w 0) && \
+	export SSL_KEY=$$(cat ./ssl.key | base64 -w 0) && \
+	envsubst < ./manifests/kots-config-self-signed.yaml > tmp_2_config.yml
+	yq m -i tmp_config.yml tmp_2_config.yml
+
 storage-config-incluster:
 	@echo "Nothing to do"
 
@@ -277,6 +296,9 @@ generate-kots-config: select-workspace check-env-cloud get-base-config
 	$(MAKE) storage-config-${cloud_storage}
 	$(MAKE) db-config-${cloud_db}
 	$(MAKE) registry-config-${cloud_registry}
+ifndef self_signed
+	$(MAKE) self-signed-config
+endif
 
 license_community_beta := "../licenses/Community (Beta).yaml"
 license_community_stable := "../licenses/Community.yaml"
@@ -323,8 +345,11 @@ check-kots-app:
 	kubectl kots get --kubeconfig=${KUBECONFIG} app gitpod -n gitpod | grep gitpod  | awk '{print $$2}' | grep "ready" || { $(MAKE) gitpod-debug-info; exit 1; }
 
 check-gitpod-installation: delete-cm-setup check-kots-app check-env-sub-domain
-	@echo "Curling http://${TF_VAR_TEST_ID}.${DOMAIN}/api/version"
-	curl -i -X GET http://${TF_VAR_TEST_ID}.${DOMAIN}/api/version || { echo "Curling Gitpod endpoint failed"; exit 1; }
+	@echo "Curling https://${TF_VAR_TEST_ID}.${DOMAIN}/api/version"
+ifndef self_signed
+	export SSL_CERT_FILE=./ca.pem && \
+endif
+	curl -i -X GET https://${TF_VAR_TEST_ID}.${DOMAIN}/api/version || { echo "Curling Gitpod endpoint failed"; exit 1; }
 
 define runtests
 	./tests.sh ${KUBECONFIG} $(1)
